name: 'manifest - zchryr'
description: 'GitHub Action to generate matrix with locations of manifest files within a repository.'
branding:
  icon: 'check'
  color: 'black'

inputs:
  manifest:
    description: 'The manifest file to search for in the directory and its subdirectories.'
    required: true
  ignore_dirs:
    description: 'Optional. A comma-separated list of directories to ignore during the search.'
    required: false
  ignore_root:
    description: 'Optional. Ignore root directory of repository if manifest is found in it.'
    required: false

outputs:
  search_results:
    description: 'JSON results of the search for the specified file.'

runs:
  using: 'node20'
  main: './dist/index.js'
