name: 'manifest - zchryr'
description: 'GitHub Action to generate matrix with locations of manifest files within a repository.'

inputs:
  manifest:
    description: 'The file to search for in the directory and its subdirectories.'
    required: true
  manifest_ignore:
    description: 'Optional. A comma-separated list of directories to ignore during the search.'
    required: false

outputs:
  search_results:
    description: 'JSON results of the search for the specified file.'

runs:
  using: 'node20'
  main: 'main.js'
