name: 'example'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    name: 'Generate Matrix'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

    steps:
      - name: Clone
        uses: actions/checkout@v3.5.3

      - name: Matrix
        id: generate
        run: |
          go run main.go

  use-matrix:
    name: 'Test'
    runs-on: ubuntu-latest
    needs: generate-matrix
    # strategy:
    #   matrix:
    #     job: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Test
        run: |
          echo ${{ needs.generate-matrix.outputs.matrix }} | jq
